### ISSUE TITLE
Running truly headless?

### ISSUE THREAD

**Issue by jmnyberg** [bioinformatics-ua/dicoogle-learning-pack#19]
Hi all.
I am trying to run a Dicoogle server from a debian 10 headless server with openjdk 11. I get the following:

johan@edge:~/Dicoogle_v2.5.0$ java -jar dicoogle.jar -s                                                                                                                 Exception in thread "main" java.awt.HeadlessException:                                                                                                                  No X11 DISPLAY variable was set, but this program performed an operation which requires it.                                                                                     at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)                                                                                at java.desktop/java.awt.Window.<init>(Window.java:548)                                                                                                                 at java.desktop/java.awt.Frame.<init>(Frame.java:423)                                                                                                                   at java.desktop/java.awt.Frame.<init>(Frame.java:388)                                                                                                                   at java.desktop/javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1919)                                                                            at java.desktop/javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1995)                                                                                at java.desktop/javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1689)                                                                                             at java.desktop/javax.swing.JOptionPane.showInputDialog(JOptionPane.java:580)                                                                                           at pt.ua.dicoogle.Main.LaunchDicoogle(Main.java:239)                                                                                                                    at pt.ua.dicoogle.Main.main(Main.java:107)   

Attemptning a fix suggested on Stackexchange gives a somewhat shorter erroe message:

johan@edge:~/Dicoogle_v2.5.0$ java -Djava.awt.headless=true -jar dicoogle.jar -s                                                                                        Exception in thread "main" java.awt.HeadlessException                                                                                                                           at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)                                                                                at java.desktop/java.awt.Window.<init>(Window.java:548)                                                                                                                 at java.desktop/java.awt.Frame.<init>(Frame.java:423)                                                                                                                   at java.desktop/java.awt.Frame.<init>(Frame.java:388)                                                                                                                   at java.desktop/javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1919)                                                                            at java.desktop/javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1995)                                                                                at java.desktop/javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1689)                                                                                             at java.desktop/javax.swing.JOptionPane.showInputDialog(JOptionPane.java:580)                                                                                           at pt.ua.dicoogle.Main.LaunchDicoogle(Main.java:239)                                                                                                                    at pt.ua.dicoogle.Main.main(Main.java:107)

Any suggestions?

**Comment by Enet4** [comment]
Hello!

Due to a quirk in version 2.5.0, Dicoogle will attempt to prompt the user for a Dicoogle instance name (often just set to the machine's host name) the first time that the server is run. This can be circumvented by providing a configuration file in advance.

Please try adding a file "config.xml" to the working directory. Below is a sample configuration file which can be adjusted to fit your use case.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Config>
  <Port>6666</Port>
  <Path>/tmp</Path>
  <IndexEffort>100</IndexEffort>
  <IndexZipFiles>true</IndexZipFiles>
  <GZipStorage>false</GZipStorage>
  <IndexAnonymous>false</IndexAnonymous>
  <MonitorWatcher>false</MonitorWatcher>
  <EncryptUsersFile>false</EncryptUsersFile>
  <WANModeEnabled>false</WANModeEnabled>
  <P2P>
    <Node>
      <name>dicoogle-local</name>
      <defined>true</defined>
    </Node>
  </P2P>
  <Storage>true</Storage>
  <DicoogleDir>/opt/storage</DicoogleDir>
  <fullContentIndex>false</fullContentIndex>
  <SaveThumbnails>true</SaveThumbnails>
  <ThumbnailsMatrix>128</ThumbnailsMatrix>
  <AETitle>DICOOGLE-STORAGE</AETitle>
  <PermitAllAETitles>true</PermitAllAETitles>
  <Service UID="1.2.840.10008.5.1.4.1.1.88.40">
    <TS>1.2.840.10008.1.2</TS>
    <TS>1.2.840.10008.1.2.1</TS>
    <TS>1.2.840.10008.1.2.4.80</TS>
    <TS>1.2.840.10008.1.2.4.50</TS>
  </Service>
  <Service UID="1.2.840.10008.5.1.4.1.1.77.1.1">
    <TS>1.2.840.10008.1.2</TS>
    <TS>1.2.840.10008.1.2.1</TS>
    <TS>1.2.840.10008.1.2.4.80</TS>
    <TS>1.2.840.10008.1.2.4.50</TS>
  </Service>
  <Service UID="1.2.840.10008.5.1.1.30">
    <TS>1.2.840.10008.1.2</TS>
    <TS>1.2.840.10008.1.2.1</TS>
    <TS>1.2.840.10008.1.2.4.80</TS>
    <TS>1.2.840.10008.1.2.4.50</TS>
  </Service>
  <LocalAETName>DicoogleT</LocalAETName>
  <QueryRetrieve>
    <DeviceDescription>Dicoogle - Server SCP</DeviceDescription>
    <QREnable>false</QREnable>
    <Port>1045</Port>
    <PermitedLocalInterfaces>any</PermitedLocalInterfaces>
    <PermitedHostnames>any</PermitedHostnames>
    <RspDelay>3</RspDelay>
    <DIMSERspTimeout>50</DIMSERspTimeout>
    <IdleTimeout>50</IdleTimeout>
    <AcceptTimeout>50</AcceptTimeout>
    <ConnectionTimeout>50</ConnectionTimeout>
    <TRANSF_CAP>1.2.840.10008.1.2.2|1.2.840.10008.1.2.1</TRANSF_CAP>
    <SOP_CLASS>1.2.840.10008.5.1.4.1.2.1.1</SOP_CLASS>
    <MAX_CLIENT_ASSOCS>22</MAX_CLIENT_ASSOCS>
    <MAX_PDU_LENGTH_RECEIVE>16360</MAX_PDU_LENGTH_RECEIVE>
    <MAX_PDU_LENGTH_SEND>16360</MAX_PDU_LENGTH_SEND>
    <!--
    <Retrieve>
      <SOPClass>1.2.840.10008.5.1.4.1.2.2.1|1.2.840.10008.5.1.4.1.2.1.1</SOPClass>
    </Retrieve>
    -->
    <options>
      <modality>
        <cfind>
          <find sop="find">Study Root Query/Retrieve Info Model</find>
          <find sop="1.2.840.10008.5.1.4.1.2.1.1">Patient Root Query/Retrieve Info Model</find>
          <find sop="1.2.840.10008.5.1.4.1.2.2.1">Study Root Query/Retrieve Info Model</find>
        </cfind>
      </modality>
      <destinations>
      </destinations>
      <CSTOREPriorities/>
    </options>
  </QueryRetrieve>
  <web>
    <server enable="true" port="8080" allowedOrigins="*"/>
  </web>
</Config>
```

**Comment by jmnyberg** [comment]
Thanks a lot!
J
