### ISSUE TITLE
Image Not Found

### ISSUE THREAD

**Issue by tchampion** [bioinformatics-ua/dicoogle-learning-pack#24]
Hello, I'm trying to set up a web interface to search and view our fluoro images.  Everything seems like it indexed appropriately and the DICOM Medadata is displayed but I cannot view the images.  Did I miss something in the configuration?  The Medadata says the modality is "RAW".  Maybe the image viewer doesn't support fluoro?

**Comment by Enet4** [comment]
I understand that you are trying to view the images from the Dicoogle web interface. Is that correct?

It is indeed possible that some images are in an encoding in which previewing is not supported right out of the box. "Image Not Found" is a bit misleading, I agree, as the image may be well indexed and available to SCUs for retrieval, but merely fail to provide a preview/thumbnail. The main attribute to look into when this happens is the _transfer syntax UID_. Dicoogle uses dcm4che, which is integrated with the JAI API for image reading and writing. There is likely a way to extend the list of image readers and writers in deployment time, but I am not completely familiar with the process.

Nevertheless, it is worth reminding that Dicoogle alone is not suitable for professional visualization. For this, it is better to couple the archive with a DICOM-compliant viewer.
