### ISSUE TITLE
wadoUriRoot , qidoRoot and wadoRoot for conecting Dicoogle to a DICOM Viewer

### ISSUE THREAD

**Issue by DenilphsonGY** [bioinformatics-ua/dicoogle-learning-pack#30]
I´m trying to conect Dicoogle to OHIF Viewer but it has a js that needs wadoUriRoot, qidoRoot and wadoRoot URL.

I saw that dcm4chee use /dcm4chee-arc/aets/DCM4CHEE/wado for the first root and /dcm4chee-arc/aets/DCM4CHEE/rs for the second, but I don't find how to do it with dicoogle. 

Is there another way to conect Dicoogle with an professional DICOM VIEWER?

**Comment by Enet4** [comment]
The open Dicoogle bundle does not include DICOMWeb services. Professional viewers would be connected either by use of C-FIND and C-MOVE DIMSE, or by extending Dicoogle with additional Web services, as done by BMD Software.
