### ISSUE TITLE
Storage Server examples

### ISSUE THREAD

**Issue by Darktuse** [bioinformatics-ua/dicoogle-learning-pack#6]
Hi,
I am trying to use 2 terminals, 1 executing dicoogle (low on hdd capacity) and the other as primary storage, but I can't get to index the files in my storage. 
Dicoogle is only executing in the first terminal and I added the second as storage server (not sure if the port is right or if i have to execute dicoogle in the second) . 
Could you help me with my problem?

**Comment by Enet4** [comment]
Hello,

I'm afraid that this concept was probably a bit misunderstood. Storage servers registered in Dicoogle are only useful as potential destinations for DICOM service requests. Namely, it would enable sending files to one or more of the registered storage servers (with a C-Move).

Indexing with Dicoogle requires that the files are available through the internal storage interface. With the basic file storage plugin, the files should be in the local file system. The easiest way to address your problem might be to deploy Dicoogle in your second server. Alternatively, one could keep a network file system in the second server and create a network-mapped directory in the first server using the operating system's own facilities.

We'll be looking for ways to make this clearer in the learning pack. Thank you for bringing this up and feel free to let us know if the above works for you.
